[env:release]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lilygo-t-display-s3
framework = arduino
lib_deps =
    LovyanGFX@1.2.19
    https://github.com/cnmat/OSC@3.5.8
build_type = release

[env:debug]
extends = env:release
monitor_filters =
    esp32_exception_decoder
    time
    direct
build_type = debug
build_flags =
    ${env.build_flags}
    -D USE_ESP_IDF_LOG
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D LOG_LOCAL_LEVEL=5
    -D CORE_DEBUG_LEVEL=3
    -D XROSSSYNC_DEBUG